name: laravel-php
type: service
from: php
title: PHP (Laravel)

containers:
- name: php
  image: wodby/laravel-php

links:
- name: storage
  title: Storage
  required: true
  selectors:
  - type: storage
- name: redis
  title: Redis
  env:
  - name: QUEUE_CONNECTION
    value: redis
  selectors:
  - type: datastore
    labels:
    - redis
  - type: datastore
    labels:
    - valkey

volumes:
- name: storage
  title: Storage
  link: storage
  shared: true
  size: 10
  path: /mnt/files
  import:
    owner: 82
    group: 82

update: auto

labels:
- laravel

options:
- version: '8.3'
  default: true
- version: '8.2'  

env:
- name: APP_KEY
  value: '{{app_key}}'
- name: LARAVEL_APP_DEBUG
  value: 'true'
  envType: dev

cron:
- name: scheduler 
  title: Task Scheduler
  command: cd "${APP_ROOT}" && php artisan schedule:run
  schedule: 0 0 * * *

derivatives:
- name: laravel-php-queue
  icon: laravel
  title: Laravel Queue
  args: ['php', 'artisan', 'queue:listen']
  type: service
  default: true
  required: false
  
build:
  dockerfile: Dockerfile
  connect: true
  templates:
  - name: boilerplate
    title: Laravel Boilerplate
    repo: https://github.com/laravel/laravel
    tag: ^11
    pipeline: pipeline.yml

tokens:
- name: app_key
  generate:
    regex: '[0-9a-z]{32}'

actions:
- name: database_migrate
  title: Run migrate
  args: 
  - php
  - artisan
  - migrate
  type: post_deploy
- name: database_seed
  title: Seed database
  depends:
  - database_migrate
  args: 
  - php
  - artisan
  - db:seed
  type: post_deploy_once
