name: php-laravel
type: service
from: php
title: PHP (Laravel)

update: auto

labels:
- laravel

options:
- version: '8.1'
  default: true

links:
- name: redis
  title: Redis
  env:
  - name: QUEUE_CONNECTION
    value: redis
  selectors:
  - type: datastore
    labels:
    - redis

derivatives:
- name: php-laravel-queue
  icon: laravel
  title: Laravel Queue
  args: ['php', 'artisan', 'queue:listen']
  type: service
  default: true
  required: false
  
build:
  connect: true
  templates:
  - name: boilerplate
    title: Laravel Boilerplate
    repo: https://github.com/rappasoft/laravel-boilerplate
    tag: ^8
    pipeline: pipeline.yml
